updating email
w3b3d3v/web3-bootcamp-platform pull request #139
Opened 2024-03-04 17:09 UTC by viniblack

## Brief Information

The type of this pull request is:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

### Fixed issues

## Details

### Before: What was the problem?

### After: How does it behave after the fixing?

### Test: How did you test the issue?

## Others

### Merging options

- [ ] Please squash the commits into a single one when merging.

### Other information

2024-03-04 18:49 UTC, danicuki requested changes

2024-03-04 18:49 UTC, danicuki commented on functions/email_templates/1_hour_to_start.js
> +  <div>Faltam poucos minutos ⌛ para o lançamento do build {nome do build} (19h horário Brasília).
não é assim que funciona o placeholder. {nome do build} não vai substituir pelo nome do build ;-)

2024-03-04 18:49 UTC, danicuki commented on functions/email_templates/1_hour_to_start.js
> +  <div>Ah! Não esquece de entrar no <a href="https://discord.gg/web3dev">nosso Discord</a>
porque mudou o link? Algum motivo?

2024-03-04 18:49 UTC, danicuki commented on functions/email_templates/on_cohort_signup.js
> +  <head>
esse HTML não tem HEAD, é html de email, acho que não faz diferença colocar nada no HEAD

2024-03-04 19:22 UTC, viniblack commented on functions/email_templates/1_hour_to_start.js
> +  <div>Faltam poucos minutos ⌛ para o lançamento do build {nome do build} (19h horário Brasília).
my bad, acabei não substituindo para o placeholder correto

2024-03-04 19:22 UTC, viniblack commented on functions/email_templates/1_hour_to_start.js
> +  <div>Ah! Não esquece de entrar no <a href="https://discord.gg/web3dev">nosso Discord</a>
Não sabia que esse link era um convite para o discord tambem

2024-06-06 15:52 UTC, danicuki commented
I will close this PR because I already reviewed the message, adding also an English version of it. It is already deployed in production

2024-06-06 15:52 UTC, closed without merging