Study groups page
w3b3d3v/web3-bootcamp-platform pull request #140
Opened 2024-05-02 15:38 UTC by nomadbitcoin

## Brief Information

The type of this pull request is:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

This PR introduces new features related to the management of study groups. The changes include:

1. **New Pages**:
   - A new page to list all study groups, allowing users to easily see all available options.
   - A new page dedicated to loading and displaying specific content for each study group.

2. **Component Enhancements**:
   - Modification of the existing `Tab` component to now load and display students who are part of courses and groups.

3. **Helper Functions**:
   - Addition of several to facilitate the addition of new courses or groups within the Firebase database. 

### Implementation Details

All the changes were made by reusing the existing logic and components of the codebase

2024-05-02 19:02 UTC, danicuki requested changes

2024-05-02 19:02 UTC, danicuki commented on lib/course.js
> +export async function getCourse(kind, identifier) {
we should rename this. `Study Groups` are not courses. I understand you intention, reusing code, but this signature confuses me. Also the implementation doesn't need this `kindToFunctionMap`. If can directly get the function from the kind. My suggestion:

```javascript
function getCourse(courseId) { }
function getStudyGroup(slug) { }

function getDocument(collection, id) { 
   return self["get" + collection](id)
} 

getDocument("StudyGroup", "DAO")
getDocument("Course", "Solidity")

2024-05-02 19:02 UTC, danicuki commented on pages/study-groups/[slug].js
> +  const group = await getCourse("group", params.slug)
lets call it "study group" and not group ;-)

2024-05-02 19:02 UTC, danicuki commented on pages/study-groups/index.js
> +    "title": "List of All Groups",
List of all Study Groups

2024-05-02 19:02 UTC, danicuki commented on pages/study-groups/index.js
> +function Groups({ AllGroups }) {
`StudyGroups`

2024-05-02 20:27 UTC, nomadbitcoin commented on components/Tabs/index.js
>  export default function Tabs({ course, isLessonPage, lessonsSubmitted, cohort }) {
I'm not sure if I got it.

Courses have an analytics structure with more data, including a list of objects with sessions, the number of students in each session and profile pictures.

Study groups will only have the number of students and their profile pictures. 

do you suggest that I just check that lessonsSubmitted and cohort are undefined and if they are assume that it is a study group?

2024-06-05 13:42 UTC, merged

2024-06-05 13:43 UTC, danicuki commented
There are a lot of things still missing here. I will add them in a comment and accept the PR. @nomadbitcoin please work on these other things in a new PR. 

- translations i18n missing. It must use the new i18n translation files and add all keys there. We also need to have description and course details, title, etc, all this in the database, one for each language.
- When subscribe to group, the page that shows up is related to builds (live, etc). It must explain about the study group 
- It is not recording in the database that this user is subscribed to the group. It must record the same way we record cohorts / courses
- getStudyGroup function is in `courses.js` file, it should be in another place