Re-design profile page
w3b3d3v/web3-bootcamp-platform pull request #85
Opened 2023-02-15 13:40 UTC by vitormancio

2023-02-15 17:51 UTC, Lorenzobattistela requested changes

2023-02-15 17:51 UTC, Lorenzobattistela commented on components/Button/ScrollDown/index.js
> +import { Button } from "@nextui-org/react"
Comment out or remove completely this piece of code since it is not being used now (maybe store code for later need)

2023-02-15 17:51 UTC, Lorenzobattistela commented on components/Card/GeneralInfo/ProfessionalData/index.js
> +          é você ? Selecione até 3 opções
Remove whitespace before `?`

2023-02-15 17:51 UTC, Lorenzobattistela commented on components/Card/GeneralInfo/ProfileFooter/index.js
> +      {/* <div className='flex justify-between gap-56 mt-4 mb-4'>
Remove commented code

2023-02-15 17:51 UTC, Lorenzobattistela commented on pages/_app.js
>        <AuthProvider>
Improve indentation (remove whitespaces)

2023-02-16 12:36 UTC, vitormancio commented
@Lorenzobattistela Thanks for comments

2023-02-16 12:36 UTC, Lorenzobattistela approved these changes

2023-02-16 12:37 UTC, merged